name: book_verse
description: "BookVerse - A professional book reading application."
# প্লে স্টোরের এরর দূর করতে versionCode বাড়িয়ে 2 করা হলো
version: 1.0.0+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.1.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  # আপনার সব বুক টেক্সট ও কভার ইমেজ ফোল্ডার পাথ আকারে দেওয়া হলো
  assets:
    - assets/books/
    - assets/images/
    - assets/icon/app_icon.png

# Launcher Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"