import '../models/book_model.dart';

class BookService {
  static List<Book> getDummyBooks() {
    return [
      Book(
        id: '1',
        title: 'পরিণীতা',
        author: 'শরৎচন্দ্র চট্টোপাধ্যায়',
        description: 'সামাজিক প্রেক্ষাপটে প্রেম ও সম্পর্কের এক কালজয়ী গল্প।',
        coverAsset: 'assets/images/porinita.png',
        rating: 4.8,
        pages: 120,
        contentPath: 'assets/books/porinita.txt',
      ),
      Book(
        id: '2',
        title: 'পুতুল নাচের ইতিকথা',
        author: 'মানিক বন্দ্যোপাধ্যায়',
        description: 'গ্রাম্য জীবনের জটিল মনস্তত্ত্ব ও কুসংস্কারের চিত্রায়ণ।',
        coverAsset: 'assets/images/putul_nacher_itikotha.png',
        rating: 4.9,
        pages: 250,
        contentPath: 'assets/books/putul_nacher_itikotha.txt',
      ),
      Book(
        id: '3',
        title: 'গর্ভধারিণী',
        author: 'সমরেশ মজুমদার',
        description: 'বিপ্লব ও জীবন সংগ্রামের এক উত্তাল কাহিনী।',
        coverAsset: 'assets/images/gorvodharini.png',
        rating: 4.7,
        pages: 320,
        contentPath: 'assets/books/gorvodharini.txt',
      ),
      Book(
        id: '4',
        title: 'উত্তরাধিকার',
        author: 'সমরেশ মজুমদার',
        description: 'অনিমেষ সিরিজের প্রথম কালজয়ী উপন্যাস।',
        coverAsset: 'assets/images/uttaradhikar.png',
        rating: 4.8,
        pages: 410,
        contentPath: 'assets/books/uttaradhikar.txt',
      ),
      Book(
        id: '5',
        title: 'কালবেলা',
        author: 'সমরেশ মজুমদার',
        description: 'বিপ্লবের পটভূমিতে মাধবীলতা ও অনিমেষের অমর প্রেম।',
        coverAsset: 'assets/images/kalbela.png',
        rating: 5.0,
        pages: 550,
        contentPath: 'assets/books/kalbela.txt',
      ),
      Book(
        id: '6',
        title: 'কালপুরুষ',
        author: 'সমরেশ মজুমদার',
        description: 'অনিমেষ ও তার ছেলে অর্কর জীবনের টানাপোড়েন।',
        coverAsset: 'assets/images/kalpurush.png',
        rating: 4.6,
        pages: 380,
        contentPath: 'assets/books/kalpurush.txt',
      ),
      Book(
        id: '7',
        title: 'সাতকাহন',
        author: 'সমরেশ মজুমদার',
        description: 'দীপাবলির জীবন সংগ্রামের এক বিশাল মহাকাব্য।',
        coverAsset: 'assets/images/satkahan.png',
        rating: 4.9,
        pages: 800,
        contentPath: 'assets/books/satkahan.txt',
      ),
      Book(
        id: '8',
        title: 'মৌষলকাল',
        author: 'সমরেশ মজুমদার',
        description: 'সমসাময়িক রাজনীতির এক নিখুঁত বিশ্লেষণ।',
        coverAsset: 'assets/images/mousholkal.png',
        rating: 4.5,
        pages: 290,
        contentPath: 'assets/books/mousholkal.txt',
      ),
      Book(
        id: '9',
        title: 'নন্দিত নরকে',
        author: 'হুমায়ূন আহমেদ',
        description: 'মধ্যবিত্ত পরিবারের হাসি-কান্নার অসাধারণ রূপায়ন।',
        coverAsset: 'assets/images/nondito_noroke.png',
        rating: 4.8,
        pages: 110,
        contentPath: 'assets/books/nondito_noroke.txt',
      ),
      Book(
        id: '10',
        title: 'শঙ্খনীল কারাগার',
        author: 'হুমায়ূন আহমেদ',
        description: 'একটি পরিবারের সুখ-দুঃখের মানবিক দলিল।',
        coverAsset: 'assets/images/shonkhonil_karagar.png',
        rating: 4.9,
        pages: 130,
        contentPath: 'assets/books/shonkhonil_karagar.txt',
      ),
      Book(
        id: '11',
        title: 'কৃষ্ণপক্ষ',
        author: 'হুমায়ূন আহমেদ',
        description: 'বিরহ এবং ভাগ্যের এক বিচিত্র গল্প।',
        coverAsset: 'assets/images/krishnopokkho.png',
        rating: 4.7,
        pages: 160,
        contentPath: 'assets/books/krishnopokkho.txt',
      ),
      Book(
        id: '12',
        title: 'মেঘ বলেছে যাব যাব',
        author: 'হুমায়ূন আহমেদ',
        description: 'মানুষের নিঃসঙ্গতা ও প্রেমের এক দীর্ঘ উপন্যাস।',
        coverAsset: 'assets/images/megh_boleche.png',
        rating: 4.8,
        pages: 280,
        contentPath: 'assets/books/megh_boleche.txt',
      ),
      Book(
        id: '13',
        title: 'সাজঘর',
        author: 'হুমায়ূন আহমেদ',
        description: 'বিচিত্র মানুষের সম্পর্কের টানাপোড়েন।',
        coverAsset: 'assets/images/sajghor.png',
        rating: 4.4,
        pages: 140,
        contentPath: 'assets/books/sajghor.txt',
      ),
      Book(
        id: '14',
        title: 'তোমাকে',
        author: 'হুমায়ূন আহমেদ',
        description: 'হৃদয়স্পর্শী এক প্রেমের উপন্যাস।',
        coverAsset: 'assets/images/tomake.png',
        rating: 4.5,
        pages: 150,
        contentPath: 'assets/books/tomake.txt',
      ),
      Book(
        id: '15',
        title: 'আয়না ঘর',
        author: 'হুমায়ূন আহমেদ',
        description: 'মানুষের মনের গহীনের রহস্যের গল্প।',
        coverAsset: 'assets/images/ayna_ghor.png',
        rating: 4.6,
        pages: 180,
        contentPath: 'assets/books/ayna_ghor.txt',
      ),
      Book(
        id: '16',
        title: 'তন্দ্রা বিলাস',
        author: 'হুমায়ূন আহমেদ',
        description: 'মিসির আলি সিরিজের একটি মনস্তাত্ত্বিক রহস্য।',
        coverAsset: 'assets/images/tondra_bilas.png',
        rating: 4.7,
        pages: 200,
        contentPath: 'assets/books/tondra_bilas.txt',
      ),
      Book(
        id: '17',
        title: 'কহেন কবি কালিদাস',
        author: 'হুমায়ূন আহমেদ',
        description: 'মিসির আলির তীক্ষ্ণ বুদ্ধির আরও এক কেস।',
        coverAsset: 'assets/images/kohen_kobi_kalidas.png',
        rating: 4.8,
        pages: 190,
        contentPath: 'assets/books/kohen_kobi_kalidas.txt',
      ),
      Book(
        id: '18',
        title: 'দারুচিনি দ্বীপ',
        author: 'হুমায়ূন আহমেদ',
        description: 'শুভ্র ও তার বন্ধুদের এক স্মরণীয় সফরের গল্প।',
        coverAsset: 'assets/images/daruchini_dwip.png',
        rating: 4.9,
        pages: 220,
        contentPath: 'assets/books/daruchini_dwip.txt',
      ),
      Book(
        id: '19',
        title: 'মেঘের ছায়া',
        author: 'হুমায়ূন আহমেদ',
        description: 'শুদ্ধতম যুবক শুভ্রর জীবনের গল্প।',
        coverAsset: 'assets/images/megher_chaya.png',
        rating: 4.6,
        pages: 170,
        contentPath: 'assets/books/megher_chaya.txt',
      ),
      Book(
        id: '20',
        title: 'রূপালী দ্বীপ',
        author: 'হুমায়ূন আহমেদ',
        description: 'শুভ্র সিরিজের চমৎকার একটি উপন্যাস।',
        coverAsset: 'assets/images/rupali_dwip.png',
        rating: 4.5,
        pages: 200,
        contentPath: 'assets/books/rupali_dwip.txt',
      ),
      Book(
        id: '21',
        title: 'শুভ্র',
        author: 'হুমায়ূন আহমেদ',
        description: 'চশমা পরা সেই শান্ত ছেলেটির গল্প।',
        coverAsset: 'assets/images/shuvro.png',
        rating: 4.8,
        pages: 180,
        contentPath: 'assets/books/shuvro.txt',
      ),
      Book(
        id: '22',
        title: 'এই শুভ্র! এই',
        author: 'হুমায়ূন আহমেদ',
        description: 'শুভ্রর জীবনের আরও কিছু রহস্য।',
        coverAsset: 'assets/images/ei_shuvro_ei.png',
        rating: 4.7,
        pages: 160,
        contentPath: 'assets/books/ei_shuvro_ei.txt',
      ),
      Book(
        id: '23',
        title: 'শুভ্র গেছে বনে',
        author: 'হুমায়ূন আহমেদ',
        description: 'শুভ্রর অরণ্য অভিযানের এক কাহিনী।',
        coverAsset: 'assets/images/shuvro_geche_bone.png',
        rating: 4.6,
        pages: 190,
        contentPath: 'assets/books/shuvro_geche_bone.txt',
      ),
      Book(
        id: '24',
        title: 'ময়ূরাক্ষী',
        author: 'হুমায়ূন আহমেদ',
        description: 'হিমু সিরিজের প্রথম এবং বিস্ময়কর উপন্যাস।',
        coverAsset: 'assets/images/moyurakkhi.png',
        rating: 5.0,
        pages: 150,
        contentPath: 'assets/books/moyurakkhi.txt',
      ),
      Book(
        id: '25',
        title: 'দরজার ওপাশে',
        author: 'হুমায়ূন আহমেদ',
        description: 'হিমুর অদ্ভুত জগত এবং তার লজিক।',
        coverAsset: 'assets/images/dorjar_opashe.png',
        rating: 4.8,
        pages: 140,
        contentPath: 'assets/books/dorjar_opashe.txt',
      ),
      Book(
        id: '26',
        title: 'হিমু',
        author: 'হুমায়ূন আহমেদ',
        description: 'মহাপুরুষ হওয়ার পথে হিমুর যাত্রা।',
        coverAsset: 'assets/images/himu.png',
        rating: 4.9,
        pages: 170,
        contentPath: 'assets/books/himu.txt',
      ),
      Book(
        id: '27',
        title: 'চলে যায় বসন্তের দিন',
        author: 'হুমায়ূন আহমেদ',
        description: 'হিমুর উদাসীন জীবনের চমৎকার এক কাহিনী।',
        coverAsset: 'assets/images/chole_jay_bosonter_din.png',
        rating: 4.7,
        pages: 160,
        contentPath: 'assets/books/chole_jay_bosonter_din.txt',
      ),
      Book(
        id: '28',
        title: 'আজ হিমুর বিয়ে',
        author: 'হুমায়ূন আহমেদ',
        description: 'হিমুর বিয়ে নিয়ে যত অদ্ভুত কাণ্ড।',
        coverAsset: 'assets/images/aj_himur_biye.png',
        rating: 4.8,
        pages: 180,
        contentPath: 'assets/books/aj_himur_biye.txt',
      ),
      Book(
        id: '29',
        title: 'দেবী',
        author: 'হুমায়ূন আহমেদ',
        description: 'রানু ও মিসির আলির রহস্যময় প্রথম মোলাকাত।',
        coverAsset: 'assets/images/debi.png',
        rating: 5.0,
        pages: 200,
        contentPath: 'assets/books/debi.txt',
      ),
      Book(
        id: '30',
        title: 'নিষাদ',
        author: 'হুমায়ূন আহমেদ',
        description: 'যুক্তি বনাম অলৌকিক ঘটনার এক চমৎকার লড়াই।',
        coverAsset: 'assets/images/nishad.png',
        rating: 4.7,
        pages: 190,
        contentPath: 'assets/books/nishad.txt',
      ),
    ];
  }

  static List<Book> searchBooks(String query) {
    return getDummyBooks()
        .where((book) =>
            book.title.toLowerCase().contains(query.toLowerCase()) ||
            book.author.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }
}